server:
  port: ${PORT:8080}

spring:
  datasource:
    url: jdbc:mysql://bil4eszxu25z22htafi0-mysql.services.clever-cloud.com:3306/bil4eszxu25z22htafi0?useSSL=true&serverTimezone=UTC
    username: ubdpfpfwoyo22pa4
    password: fwvOY69qZpUIfbbnY1Vr
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10
      max-lifetime: 300000
      idle-timeout: 60000
      connection-timeout: 10000

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

# Logging configuration (optional)
logging:
  level:
    root: INFO
    org.hibernate.SQL: WARN
    org.hibernate.type.descriptor.sql.BasicBinder: WARN

# Application-specific config (optional)
cinehub:
  api:
    version: v1
