server:
  port: ${PORT:8080}

spring:
  datasource:
    url: jdbc:mysql://ballast.proxy.rlwy.net:58851/railway?serverTimezone=UTC
    username: root
    password: YLYkojblejYcQCRnTtAcAZXSeOTkQRDF
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

# Logging configuration (optional)
logging:
  level:
    root: INFO
    org.hibernate.SQL: WARN
    org.hibernate.type.descriptor.sql.BasicBinder: WARN

# Application-specific config (optional)
cinehub:
  api:
    version: v1
